[package]
name = "CyberSecurity"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto-bigint = "0.6.1"
crypto-primes = {version = "0.6.2", features = ["default-rng", "multicore"]}
rand = "0.8.0"
iced = {version = "0.13.1", features = ["debug", "image"]}
postgres = "0.19.12"