name: Rust

on:
  push:
    branches: [ "master", "development", "release" ]
  pull_request:
    branches: [ "master", "release" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    name: Test on node ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build on ${{ matrix.os }}
      run: cargo build --verbose
    - name: Run tests on ${{ matrix.os }}
      run: cargo test --verbose -- --test-threads=1
   
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Documentation forming
      run: cargo doc --no-deps
    - name: Add redirect
      run: echo '<meta http-equiv="refresh" content="0;url=CyberSecurity/index.html">' > target/doc/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc

  automerge:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4 
    - name: automerge
      run: gh pr merge ${{ github.event.pull_request.number }} --merge
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
